# Generated by Django 4.0.5 on 2022-06-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
