# Generated by Django 4.0.5 on 2022-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
    ]
