# Generated by Django 4.0.5 on 2022-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
